{
  config,
  lib,
  pkgs, # From flake.nix
  pkgsUnstable,
  nur,
  ...
}:
# Run the following command to build the NixOS configuration:
#  $ sudo nixos-rebuild switch --flake '.#yiyiwang-thinkpad'
#
# If `nixos-switch` or `nixos-install` cannot fetch `cache.nixos.org`, then
# add `--option substituters "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store"`
#
# To connect to wifi using command line, run `nmtui`
#
{
  imports = [
    # Include the results of the hardware scan
    # This file is generated by `nixos-generate-config --root /mnt`
    # and should be located at `/etc/nixos/hardware-configuration.nix`
    ./hardware-configuration.nix

    # Redis configuration
    # Not working well. Use https://hub.docker.com/r/bitnami/redis-cluster/ instead.
    # ../../services/redis.nix
    # Postgresql configuration
    ../../services/postgresql.nix
    # Neo4j configuration
    ../../services/neo4j.nix
    # pgadmin configuration
    ../../services/pgadmin.nix
    # wireguard configuration
    ../../services/wireguard.nix
  ];

  # Use the GRUB 2 boot loader
  boot.loader.grub = {
    enable = true;
    # version = 2; # Deprecated
    useOSProber = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    # Define on which hard drive you want to install Grub.
    device = "nodev";
    # Only allow maximum 6 boot entries
    configurationLimit = 6;
    # set $FS_UUID to the UUID of the EFI partition
    # Run `sudo blkid` to see the UUID
    # https://nixos.wiki/wiki/Dual_Booting_NixOS_and_Windows
    # https://askubuntu.com/questions/661947/add-windows-10-to-grub-os-list
    # https://askubuntu.com/questions/1271907/dualboot-ubuntu-windows-error-file-efi-microsoft-boot-bootmgfw-efi-not-fou
    ## extraEntries = ''
    ##   menuentry "Windows" {
    ##     insmod part_gpt
    ##     insmod ntfs
    ##     insmod search_fs_uuid
    ##     insmod chain
    ##     search --no-floppy --set=root --fs-uuid e8baa74f-5d51-455c-836f-2ae323c62535
    ##     chainloader /boot/EFI/Windows/Boot/bootmgfw.efi
    ##   }
    ## '';
  };
  boot.loader.efi = {
    efiSysMountPoint = "/boot";
    canTouchEfiVariables = false;
  };
  # Disable the ipv6.
  # This is necessary to be used together with the `networking.enableIPv6` option.
  ## boot.kernelParams = [ "ipv6.disable=1" ];

  system = {
    copySystemConfiguration = false;
    stateVersion = "22.05";
  };

  # networking.hostName = "yiyiwang-thinkpad"; # Define your hostname.
  # Run `sudo nmtui` to activate connection to Wifi
  networking.networkmanager.enable = true; # Easiest to use and most distros use this by default.
  ## networking.enableIPv6 = false; # Disable IPv6
  networking.nameservers = [
    "8.8.8.8"
    "8.8.4.4"
  ];

  # Set my time zone
  time.timeZone = "Asia/Shanghai";

  # Enable the X11 windowing system
  services.xserver.enable = true;

  # Intel
  services.xserver.videoDrivers = [ "modesetting" ];

  # Enable the GNOME Desktop Environment
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome = {
    enable = true;
    extraGSettingsOverridePackages = [ pkgs.mutter ];
    extraGSettingsOverrides = ''
      [org.gnome.mutter]
      experimental-features=['scale-monitor-framebuffer']
    '';
  };
  programs.dconf.enable = true;

  # Enable the gnome keyring
  services.gnome.gnome-keyring.enable = true;

  # https://nixos.wiki/wiki/Xorg
  # Enable HiDPI
  # bigger tty fonts
  # hardware.video.hidpi.enable = true; # <= no longer has effect
  console.font = "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
  # services.xserver.dpi = 180;
  environment.variables = {
    # GDK_SCALE = "2";
    # GDK_DPI_SCALE = "0.5";
    _JAVA_OPTIONS = "-Dsun.java2d.uiScale=2";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound
  # DEPRECATED
  # sound.enable = true;
  # hardware.pulseaudio.enable = true;

  # Enable bluetooth
  hardware.bluetooth.enable = true;

  # Enable touchpad support (enabled default in most desktopManager).
  services.libinput.enable = true;

  # Environment variables
  environment.variables.EDITOR = "nvim";

  # Enable XWayland to fix some blurry problem
  # for certain applications such as eletron and chrome.
  environment.sessionVariables.NIXOS_OZONE_WL = "1";

  # Packages to install
  environment.systemPackages = with pkgs; [
    # Gnome related
    gnome-shell
    gnome-tweaks
    adwaita-icon-theme
    gnomeExtensions.lunar-calendar
    gnomeExtensions.proxy-switcher
    gnomeExtensions.dash-to-dock
    gnomeExtensions.dash-to-panel
    gnomeExtensions.custom-hot-corners-extended
    gnomeExtensions.kimpanel # for input method
    ## Install Flat Remix GNOME/GDM  https://www.gnome-look.org/p/1013030
    gnomeExtensions.user-themes

    # Hyperland
    ## kitty # required for the default hyperland config

    # Tools/Apps
    ## libsForQt514.kolourpaint # Broken
    ## krita ## Painting tool
    ## okular
    # filezilla
    # peek
    # kooha
    # pgadmin4
    # calibre
    # wkhtmltopdf # NOTE: This will build qtwebkit-5.212.0-alpha4 and will take long time.

    ## Graphql IDEs
    # altair

    # Java
    # jetbrains.idea-community
    # maven

    # Communication
    # tdesktop
    # discord
    # teams

    # Nur
    pkgs.nur.repos.mic92.hello-nur

    # Gnome app
    # evince # document viewer

    # Game engine
    # godot
    # godot-export-templates
    # pixelorama
  ];

  # Enable polkit
  security.polkit.enable = true;

  # Enable flatpak
  services.flatpak.enable = true;

  # Enable trezor hardware wallet
  services.trezord.enable = true;

  # V2ray
  ## services.v2ray = {
  ##   enable = true;
  ##   configFile = "/home/yiyiwang/.config/v2ray/vmess4.json";
  ## };

  # Steam for gaming
  # As downloading steam will cause SSL error in China,
  # after we `sudo su` as root user, we have to run the following to set proxy, eg:
  #   $ export HTTP_PROXY=http://127.0.0.1:8889
  #   $ export HTTPS_PROXY=http://127.0.0.1:8889
  #   $ export http_proxy=http://127.0.0.1:8889
  #   $ export https_proxy=http://127.0.0.1:8889
  # After installation, we have to start Steam from the command line with the proxy env set as well:
  #   $ steam
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true; # Open ports in the firewall for Steam Remote Play
    dedicatedServer.openFirewall = true; # Open ports in the firewall for Source Dedicated Server
  };

  programs.clash-verge = {
    enable = true;
    package = pkgsUnstable.clash-verge-rev;
  };

  # Enable ZSH
  programs.zsh.enable = true;
  users.defaultUserShell = pkgs.zsh;
  # Hack to set /etc/shells as not symbolic link
  # We need to do this because the `flatpak run` cannot mount the symbolic link
  environment.etc.shells.mode = "0666";
  # https://github.com/NixOS/nixpkgs/issues/189851
  # https://discourse.nixos.org/t/open-links-from-flatpak-via-host-firefox/15465/8
  systemd.user.extraConfig = ''
    DefaultEnvironment="PATH=/run/current-system/sw/bin"
  '';

  # Enable xdg related
  xdg.portal.enable = true;

  # Define a user account.
  users.users.yiyiwang = {
    isNormalUser = true;
    extraGroups = [
      "wheel" # Enable 'sudo' for the user;
      "docker" # Adding users to the `docker` group will provide them access to the socket:
      "neo4j"
    ];
  };

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  programs.mtr.enable = true;
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };

  # Enable the hyperland
  ## programs.hyprland = {
  ##   enable = true;
  ##   xwayland.enable = true;
  ##   package = pkgs.hyprland;
  ## };

  # Enable SSH
  services.openssh.enable = true;

  # Enable Chinese input
  i18n = {
    defaultLocale = "en_US.UTF-8"; # "zh_CN.UTF-8";
    inputMethod = {
      # enabled = "ibus";
      # ibus.engines = with pkgs.ibus-engines; [ libpinyin ];
      type = "fcitx5";
      enable = true;
      fcitx5.waylandFrontend = true;
      fcitx5.addons = with pkgs; [
        fcitx5-gtk # alternatively, kdePackages.fcitx5-qt
        fcitx5-chinese-addons
        # table input method support
        # Search for `pinyin` in fcitx-configtool

        # fcitx5-nord # a color theme
        fcitx5-material-color
      ];
    };
  };
  fonts = {
    fontDir.enable = true;
    enableDefaultPackages = true;
    packages = with pkgs; [
      hack-font
      jetbrains-mono
      # (nerdfonts.override {
      #   fonts = [
      #     "FiraCode"
      #     "DroidSansMono"
      #     "Ubuntu"
      #     "UbuntuMono"
      #   ];
      # })
      noto-fonts
      noto-fonts-cjk-sans
      noto-fonts-cjk-serif
      noto-fonts-emoji
      sarasa-gothic # 更纱黑体
      source-code-pro
      ubuntu_font_family
    ];
    fontconfig = {
      # 测试字体 👹
      defaultFonts = {
        emoji = [ "Noto Color Emoji" ];
        serif = [ "Ubuntu Regular" ];
        sansSerif = [ "Sans Regular" ];
        monospace = [ "Ubuntu Mono Regular" ];
      };
      antialias = true;
      hinting.enable = true;
      # hinting.style = "slight";
    };
  };

  # Virtualization
  virtualisation = {
    # https://nixos.wiki/wiki/WayDroid
    # Run the following to init:
    # $ sudo waydroid init -c https://waydroid.bardia.tech/OTA/system -v https://waydroid.bardia.tech/OTA/vendor
    # After intalling:
    # $ sudo systemctl start waydroid-container
    # $ waydroid show-full-ui
    ## waydroid = {
    ##   enable = true;
    ## };
    docker = {
      enable = true;
      daemon.settings = {
        registry-mirrors = [
          # 国内 dockerhub 镜像 https://blog.csdn.net/buluxianfeng/article/details/143977194
          # "https://docker.unsee.tech"
          # "https://dockerpull.org"
          # "https://dockerhub.icu"
          # "https://hub.rat.dev"
          # "https://hub.xdark.top"
          "https://hub.littlediary.cn"
        ];
      };
    };
    # lxd = { enable = true; };
  };

  # Bind some directories
  system.fsPackages = [ pkgs.bindfs ];
  fileSystems =
    let
      mkRoSymBind = path: {
        device = path;
        fsType = "fuse.bindfs";
        options = [
          "ro"
          "resolve-symlinks"
          "x-gvfs-hide"
        ];
      };
      aggregatedFonts = pkgs.buildEnv {
        name = "system-fonts";
        paths = config.fonts.packages;
        pathsToLink = [ "/share/fonts" ];
      };
    in
    {
      # Create an FHS mount to support flatpak host icons/fonts
      "/usr/share/icons" = mkRoSymBind (config.system.path + "/share/icons");
      "/usr/share/fonts" = mkRoSymBind (aggregatedFonts + "/share/fonts");
    };

  # Nix settings
  nix.settings = {
    # nixPath = [ "nixpkgs=${nixpkgs}" ];
    auto-optimise-store = true;
    substituters = lib.mkForce [
      # BROKEN: "https://mirror.sjtu.edu.cn/nix-channels/store"
      "https://mirrors.ustc.edu.cn/nix-channels/store"
      "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store" # <- This is very slow
      "https://cache.nixos.org"
    ];
    trusted-users = [ "@wheel" ];
    experimental-features = [
      "nix-command"
      "flakes"
    ];
  };

  # Nixpkgs settings
  nixpkgs.overlays = [ nur.overlay ];
  nixpkgs.config = {
    allowUnfree = true;
    # allowBroken = true;
    # allowUnsupportedSystem = true;
    permittedInsecurePackages = [
      "electron-12.2.3"
      "electron-24.8.6"
      "electron-25.9.0"
      "qtwebkit-5.212.0-alpha4"
    ];
  };

}
